### ISSUE TITLE
Babel Core error on install and start in algorithms repo

### ISSUE THREAD

**Issue by JackHowa** [btholt/complete-intro-to-computer-science#30]
Was getting an error on start: 

```
@JackHowa ➜ /workspaces/algorithms-exercises (main) $ npm start

> algorithms-exercises@1.0.0 start /workspaces/algorithms-exercises
> parcel index.html

ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/transformer-babel: babelCore(...).loadPartialConfigAsync is not a function
TypeError: babelCore(...).loadPartialConfigAsync is not a function
    at load (/workspaces/algorithms-exercises/node_modules/@parcel/transformer-babel/lib/config.js:115:41)
    at loadConfig (/workspaces/algorithms-exercises/node_modules/@parcel/transformer-babel/lib/BabelTransformer.js:66:30)
    at Transformation.loadTransformerConfig (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:741:13)
    at Transformation.loadPipeline (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:679:31)
    at async Transformation.loadNextPipeline (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:717:24)
    at async Transformation.runPipelines (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:434:24)
    at async Transformation.run (/workspaces/algorithms-exercises/node_modules/@parcel/core/lib/Transformation.js:316:19)
    at async Child.handleRequest (/workspaces/algorithms-exercises/node_modules/@parcel/workers/lib/child.js:255:9)

```

Noticed a peer dependency needed updating via `npm i`

```
npm WARN @parcel/babel-preset-env@2.0.0-beta.2 requires a peer of @babel/core@^7.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN @parcel/transformer-babel@2.0.0-beta.2 requires a peer of @babel/core@^7.12.0 but none is installed. You must install peer dependencies yourself.
```

fixed in https://github.com/btholt/algorithms-exercises/pull/20

**Comment by JackHowa** [comment]
fixed!
